sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
branches:
  only:
    - master
  except:
    - /^v[0-9]/
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
